# Generated by Django 3.2.5 on 2022-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(),
        ),
    ]
