# Generated by Django 3.2.5 on 2022-04-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_date_of_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_date',
        ),
    ]
